import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from '../context/CartContext';
import { CartUIProvider } from '../context/CartUIContext';
import Cart from '../components/Cart';
import MainContainer from '../components/MainContainer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <CartUIProvider>
            <MainContainer>
              <div className="flex">
                <main className="flex-1 min-h-screen">
                  {children}
                </main>
              </div>
            </MainContainer>
            <Cart />
          </CartUIProvider>
        </CartProvider>
      </body>
    </html>
  )
}
